[2021-01-25 15:44:10,292] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_result_interaction 2021-01-25T15:43:26.751393+00:00 [queued]>
[2021-01-25 15:44:10,347] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_result_interaction 2021-01-25T15:43:26.751393+00:00 [queued]>
[2021-01-25 15:44:10,348] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 15:44:10,349] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-01-25 15:44:10,349] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 15:44:10,405] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): clean_data_search_result_interaction> on 2021-01-25T15:43:26.751393+00:00
[2021-01-25 15:44:10,411] {standard_task_runner.py:54} INFO - Started process 48627 to run task
[2021-01-25 15:44:10,507] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'clean_data_search_result_interaction', '2021-01-25T15:43:26.751393+00:00', '--job_id', '12', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmpmkwhsuwj']
[2021-01-25 15:44:10,513] {standard_task_runner.py:78} INFO - Job 12: Subtask clean_data_search_result_interaction
[2021-01-25 15:44:10,585] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.clean_data_search_result_interaction 2021-01-25T15:43:26.751393+00:00 [running]> 3f8da9634a9c
[2021-01-25 15:44:10,668] {taskinstance.py:1150} ERROR - 'Series' object has no attribute 'dupilcated'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_clean.py", line 116, in clean_data_df
    duplicate_search_id = df['search_id'].dupilcated().any()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'dupilcated'
[2021-01-25 15:44:10,679] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=clean_data, task_id=clean_data_search_result_interaction, execution_date=20210125T154326, start_date=20210125T154410, end_date=20210125T154410
[2021-01-25 15:44:15,168] {local_task_job.py:102} INFO - Task exited with return code 1
