[2021-01-25 15:44:01,799] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_request 2021-01-25T15:43:26.751393+00:00 [queued]>
[2021-01-25 15:44:01,853] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_request 2021-01-25T15:43:26.751393+00:00 [queued]>
[2021-01-25 15:44:01,854] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 15:44:01,854] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-01-25 15:44:01,855] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 15:44:01,901] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): clean_data_search_request> on 2021-01-25T15:43:26.751393+00:00
[2021-01-25 15:44:01,905] {standard_task_runner.py:54} INFO - Started process 48621 to run task
[2021-01-25 15:44:01,953] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'clean_data_search_request', '2021-01-25T15:43:26.751393+00:00', '--job_id', '11', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmp4t2gwuh5']
[2021-01-25 15:44:01,958] {standard_task_runner.py:78} INFO - Job 11: Subtask clean_data_search_request
[2021-01-25 15:44:02,054] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.clean_data_search_request 2021-01-25T15:43:26.751393+00:00 [running]> 3f8da9634a9c
[2021-01-25 15:44:02,152] {taskinstance.py:1150} ERROR - 'Series' object has no attribute 'dupilcated'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_clean.py", line 116, in clean_data_df
    duplicate_search_id = df['search_id'].dupilcated().any()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'dupilcated'
[2021-01-25 15:44:02,164] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=clean_data, task_id=clean_data_search_request, execution_date=20210125T154326, start_date=20210125T154401, end_date=20210125T154402
[2021-01-25 15:44:06,770] {local_task_job.py:102} INFO - Task exited with return code 1
