[2021-01-25 17:03:03,176] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_result_interaction 2021-01-25T16:57:17.466260+00:00 [queued]>
[2021-01-25 17:03:03,225] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.clean_data_search_result_interaction 2021-01-25T16:57:17.466260+00:00 [queued]>
[2021-01-25 17:03:03,225] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 17:03:03,226] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2021-01-25 17:03:03,227] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 17:03:03,281] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): clean_data_search_result_interaction> on 2021-01-25T16:57:17.466260+00:00
[2021-01-25 17:03:03,287] {standard_task_runner.py:54} INFO - Started process 51028 to run task
[2021-01-25 17:03:03,325] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'clean_data_search_result_interaction', '2021-01-25T16:57:17.466260+00:00', '--job_id', '30', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmplw2slszf']
[2021-01-25 17:03:03,329] {standard_task_runner.py:78} INFO - Job 30: Subtask clean_data_search_result_interaction
[2021-01-25 17:03:03,401] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.clean_data_search_result_interaction 2021-01-25T16:57:17.466260+00:00 [running]> 3f8da9634a9c
[2021-01-25 17:03:03,868] {data_clean.py:140} INFO - All click data has a corresponding search request
[2021-01-25 17:03:03,869] {data_clean.py:142} INFO - There were more search requests than clicked on data
[2021-01-25 17:03:03,869] {logging_mixin.py:112} WARNING - --- Logging error ---
[2021-01-25 17:03:03,871] {logging_mixin.py:112} WARNING - Traceback (most recent call last):
[2021-01-25 17:03:03,871] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
[2021-01-25 17:03:03,872] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
[2021-01-25 17:03:03,873] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
[2021-01-25 17:03:03,873] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
[2021-01-25 17:03:03,874] {logging_mixin.py:112} WARNING - TypeError: not all arguments converted during string formatting
[2021-01-25 17:03:03,874] {logging_mixin.py:112} WARNING - Call stack:
[2021-01-25 17:03:03,880] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/bin/airflow", line 37, in <module>
    args.func(args)
[2021-01-25 17:03:03,881] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 76, in wrapper
    return f(*args, **kwargs)
[2021-01-25 17:03:03,881] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 579, in run
    _run(args, dag, ti)
[2021-01-25 17:03:03,882] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 475, in _run
    run_job.run()
[2021-01-25 17:03:03,882] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 218, in run
    self._execute()
[2021-01-25 17:03:03,883] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/local_task_job.py", line 94, in _execute
    self.task_runner.start()
[2021-01-25 17:03:03,883] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 43, in start
    self.process = self._start_by_fork()
[2021-01-25 17:03:03,884] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 86, in _start_by_fork
    args.func(args, dag=self.dag)
[2021-01-25 17:03:03,884] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 76, in wrapper
    return f(*args, **kwargs)
[2021-01-25 17:03:03,885] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 579, in run
    _run(args, dag, ti)
[2021-01-25 17:03:03,885] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 480, in _run
    pool=args.pool,
[2021-01-25 17:03:03,886] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
[2021-01-25 17:03:03,886] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
[2021-01-25 17:03:03,887] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
[2021-01-25 17:03:03,887] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2021-01-25 17:03:03,887] {logging_mixin.py:112} WARNING -   File "/opt/airflow/dags/data_clean.py", line 146, in clean_data_df
    logging.info(tablename, ": Columns: ", cols_cleaned)
[2021-01-25 17:03:03,888] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1902, in info
    root.info(msg, *args, **kwargs)
[2021-01-25 17:03:03,888] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1308, in info
    self._log(INFO, msg, args, **kwargs)
[2021-01-25 17:03:03,889] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
[2021-01-25 17:03:03,889] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
[2021-01-25 17:03:03,889] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
[2021-01-25 17:03:03,890] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
[2021-01-25 17:03:03,890] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/log/file_task_handler.py", line 63, in emit
    self.handler.emit(record)
[2021-01-25 17:03:03,890] {logging_mixin.py:112} WARNING - Message: 'search_result_interaction'
Arguments: (': Columns: ', ['Unnamed: 0', 'search_id', 'search_query', 'ts_x', 'cuid', 'total', 'ts_y', 'cid', 'position'])
[2021-01-25 17:03:03,900] {logging_mixin.py:112} WARNING - --- Logging error ---
[2021-01-25 17:03:03,900] {logging_mixin.py:112} WARNING - Traceback (most recent call last):
[2021-01-25 17:03:03,901] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
[2021-01-25 17:03:03,902] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
[2021-01-25 17:03:03,902] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
[2021-01-25 17:03:03,903] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
[2021-01-25 17:03:03,903] {logging_mixin.py:112} WARNING - TypeError: not all arguments converted during string formatting
[2021-01-25 17:03:03,904] {logging_mixin.py:112} WARNING - Call stack:
[2021-01-25 17:03:03,906] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/bin/airflow", line 37, in <module>
    args.func(args)
[2021-01-25 17:03:03,906] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 76, in wrapper
    return f(*args, **kwargs)
[2021-01-25 17:03:03,907] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 579, in run
    _run(args, dag, ti)
[2021-01-25 17:03:03,907] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 475, in _run
    run_job.run()
[2021-01-25 17:03:03,908] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 218, in run
    self._execute()
[2021-01-25 17:03:03,908] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/local_task_job.py", line 94, in _execute
    self.task_runner.start()
[2021-01-25 17:03:03,909] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 43, in start
    self.process = self._start_by_fork()
[2021-01-25 17:03:03,909] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 86, in _start_by_fork
    args.func(args, dag=self.dag)
[2021-01-25 17:03:03,910] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 76, in wrapper
    return f(*args, **kwargs)
[2021-01-25 17:03:03,910] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 579, in run
    _run(args, dag, ti)
[2021-01-25 17:03:03,911] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 480, in _run
    pool=args.pool,
[2021-01-25 17:03:03,912] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
[2021-01-25 17:03:03,912] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
[2021-01-25 17:03:03,913] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
[2021-01-25 17:03:03,913] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2021-01-25 17:03:03,914] {logging_mixin.py:112} WARNING -   File "/opt/airflow/dags/data_clean.py", line 154, in clean_data_df
    logging.error("Original columns are not in tact in: ", tablename)
[2021-01-25 17:03:03,915] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1869, in error
    root.error(msg, *args, **kwargs)
[2021-01-25 17:03:03,915] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
[2021-01-25 17:03:03,916] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
[2021-01-25 17:03:03,916] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
[2021-01-25 17:03:03,917] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
[2021-01-25 17:03:03,918] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
[2021-01-25 17:03:03,918] {logging_mixin.py:112} WARNING -   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/log/file_task_handler.py", line 63, in emit
    self.handler.emit(record)
[2021-01-25 17:03:03,919] {logging_mixin.py:112} WARNING - Message: 'Original columns are not in tact in: '
Arguments: ('search_result_interaction',)
[2021-01-25 17:03:03,925] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py:2612: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,
[2021-01-25 17:03:04,086] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-01-25 17:03:04,100] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=clean_data_search_result_interaction, execution_date=20210125T165717, start_date=20210125T170303, end_date=20210125T170304
[2021-01-25 17:03:08,142] {local_task_job.py:102} INFO - Task exited with return code 0
